#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("GooglePlayServicesTest.Resource", IsApplication=true)]

namespace GooglePlayServicesTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int layers_array = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010012
			public const int circleCrop = 2130771986;
			
			// aapt resource value: 0x7f010011
			public const int imageAspectRatio = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int imageAspectRatioAdjust = 2130771984;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int common_signin_btn_text_dark = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_signin_btn_text_light = 2131034123;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int badge_nsw = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int badge_qld = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int badge_sa = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int badge_victoria = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int badge_wa = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int balloon_disclosure = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int balloon_overlay_bg_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int balloon_overlay_close = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int balloon_overlay_focused = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int balloon_overlay_unfocused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_full_open_on_phone = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_ic_googleplayservices = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_disabled_dark = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_icon_disabled_focus_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_icon_disabled_light = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_icon_focus_dark = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_icon_focus_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_icon_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_icon_normal_dark = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_icon_normal_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_icon_pressed_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_icon_pressed_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_disabled_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_signin_btn_text_disabled_focus_dark = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_signin_btn_text_disabled_focus_light = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_signin_btn_text_disabled_light = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_signin_btn_text_focus_dark = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_signin_btn_text_focus_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_signin_btn_text_light = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_signin_btn_text_normal_dark = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_signin_btn_text_normal_light = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_signin_btn_text_pressed_dark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_signin_btn_text_pressed_light = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int custom_info_bubble = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int icon = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int newark_nj_1922 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int powered_by_google_dark = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int powered_by_google_light = 2130837545;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08003d
			public const int address_text = 2131230781;
			
			// aapt resource value: 0x7f080007
			public const int adjust_height = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int adjust_width = 2131230728;
			
			// aapt resource value: 0x7f080031
			public const int alphaSeekBar = 2131230769;
			
			// aapt resource value: 0x7f080011
			public const int animate = 2131230737;
			
			// aapt resource value: 0x7f08001a
			public const int badge = 2131230746;
			
			// aapt resource value: 0x7f080001
			public const int balloon_close = 2131230721;
			
			// aapt resource value: 0x7f08000c
			public const int balloon_disclosure = 2131230732;
			
			// aapt resource value: 0x7f080000
			public const int balloon_inner_layout = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int balloon_item_snippet = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int balloon_item_title = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int balloon_main_layout = 2131230729;
			
			// aapt resource value: 0x7f080019
			public const int bondi = 2131230745;
			
			// aapt resource value: 0x7f08001f
			public const int camera_text = 2131230751;
			
			// aapt resource value: 0x7f080040
			public const int compass_toggle = 2131230784;
			
			// aapt resource value: 0x7f080028
			public const int custom_info_contents = 2131230760;
			
			// aapt resource value: 0x7f080029
			public const int custom_info_window = 2131230761;
			
			// aapt resource value: 0x7f080026
			public const int custom_info_window_options = 2131230758;
			
			// aapt resource value: 0x7f080027
			public const int default_info_window = 2131230759;
			
			// aapt resource value: 0x7f080020
			public const int description = 2131230752;
			
			// aapt resource value: 0x7f080035
			public const int et_from = 2131230773;
			
			// aapt resource value: 0x7f080038
			public const int et_to = 2131230776;
			
			// aapt resource value: 0x7f08003c
			public const int get_address_button = 2131230780;
			
			// aapt resource value: 0x7f08003e
			public const int get_distance = 2131230782;
			
			// aapt resource value: 0x7f080030
			public const int hueSeekBar = 2131230768;
			
			// aapt resource value: 0x7f080002
			public const int hybrid = 2131230722;
			
			// aapt resource value: 0x7f080022
			public const int layers_spinner = 2131230754;
			
			// aapt resource value: 0x7f08003b
			public const int location_text = 2131230779;
			
			// aapt resource value: 0x7f08000d
			public const int map = 2131230733;
			
			// aapt resource value: 0x7f08002c
			public const int map1 = 2131230764;
			
			// aapt resource value: 0x7f08002d
			public const int map2 = 2131230765;
			
			// aapt resource value: 0x7f08002e
			public const int map3 = 2131230766;
			
			// aapt resource value: 0x7f08002f
			public const int map4 = 2131230767;
			
			// aapt resource value: 0x7f08002a
			public const int map_container = 2131230762;
			
			// aapt resource value: 0x7f08002b
			public const int map_container2 = 2131230763;
			
			// aapt resource value: 0x7f080024
			public const int my_location = 2131230756;
			
			// aapt resource value: 0x7f080041
			public const int mylocationbutton_toggle = 2131230785;
			
			// aapt resource value: 0x7f080042
			public const int mylocationlayer_toggle = 2131230786;
			
			// aapt resource value: 0x7f080003
			public const int none = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int normal = 2131230724;
			
			// aapt resource value: 0x7f080033
			public const int rel1 = 2131230771;
			
			// aapt resource value: 0x7f080036
			public const int rel12 = 2131230774;
			
			// aapt resource value: 0x7f080039
			public const int rel2 = 2131230777;
			
			// aapt resource value: 0x7f08001d
			public const int root = 2131230749;
			
			// aapt resource value: 0x7f080046
			public const int rotate_toggle = 2131230790;
			
			// aapt resource value: 0x7f080005
			public const int satellite = 2131230725;
			
			// aapt resource value: 0x7f080014
			public const int scroll_down = 2131230740;
			
			// aapt resource value: 0x7f080012
			public const int scroll_left = 2131230738;
			
			// aapt resource value: 0x7f080015
			public const int scroll_right = 2131230741;
			
			// aapt resource value: 0x7f080043
			public const int scroll_toggle = 2131230787;
			
			// aapt resource value: 0x7f080013
			public const int scroll_up = 2131230739;
			
			// aapt resource value: 0x7f08001c
			public const int snippet = 2131230748;
			
			// aapt resource value: 0x7f080010
			public const int stop_animation = 2131230736;
			
			// aapt resource value: 0x7f080018
			public const int sydney = 2131230744;
			
			// aapt resource value: 0x7f08001e
			public const int tap_text = 2131230750;
			
			// aapt resource value: 0x7f080006
			public const int terrain = 2131230726;
			
			// aapt resource value: 0x7f080045
			public const int tilt_toggle = 2131230789;
			
			// aapt resource value: 0x7f08001b
			public const int title = 2131230747;
			
			// aapt resource value: 0x7f080025
			public const int top_text = 2131230757;
			
			// aapt resource value: 0x7f080023
			public const int traffic = 2131230755;
			
			// aapt resource value: 0x7f080021
			public const int transparencySeekBar = 2131230753;
			
			// aapt resource value: 0x7f08003a
			public const int tvDuration = 2131230778;
			
			// aapt resource value: 0x7f080034
			public const int tv_from = 2131230772;
			
			// aapt resource value: 0x7f08000e
			public const int tv_latlongAddress = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int tv_streetAddress = 2131230735;
			
			// aapt resource value: 0x7f080037
			public const int tv_to = 2131230775;
			
			// aapt resource value: 0x7f080032
			public const int widthSeekBar = 2131230770;
			
			// aapt resource value: 0x7f08003f
			public const int zoom_buttons_toggle = 2131230783;
			
			// aapt resource value: 0x7f080044
			public const int zoom_gestures_toggle = 2131230788;
			
			// aapt resource value: 0x7f080016
			public const int zoom_in = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int zoom_out = 2131230743;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ballon_overlay = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int basic_demo = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int camera_demo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int custom_info_contents = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int custom_info_window = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int empty = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int events_demo = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int feature = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ground_overlay_demo = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int layers_demo = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int main = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int marker_demo = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int multimap_demo = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int options_demo = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int polygon_demo = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int polyline_basic_demo = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int polyline_demo = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int raw_mapview_demo = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int ui_settings_demo = 2130903058;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040022
			public const int alpha = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int animate = 2130968611;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040026
			public const int basic_description = 2130968614;
			
			// aapt resource value: 0x7f040024
			public const int basic_map = 2130968612;
			
			// aapt resource value: 0x7f040027
			public const int camera_demo = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int camera_description = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int clear_map = 2130968617;
			
			// aapt resource value: 0x7f040004
			public const int common_android_wear_notification_needs_update_text = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int common_android_wear_update_text = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int common_android_wear_update_title = 2130968591;
			
			// aapt resource value: 0x7f04001f
			public const int common_google_play_services_api_unavailable_text = 2130968607;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_enable_button = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_error_notification_requested_by_msg = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_install_button = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_install_text_phone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_install_text_tablet = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int common_google_play_services_invalid_account_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_invalid_account_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_needs_enabling_title = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_network_error_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_network_error_title = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_needs_update_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_notification_ticker = 2130968578;
			
			// aapt resource value: 0x7f040021
			public const int common_google_play_services_sign_in_failed_text = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int common_google_play_services_sign_in_failed_title = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_unknown_issue = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unsupported_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_unsupported_title = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_update_button = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_update_title = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_updating_title = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public const int common_open_on_phone = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int common_signin_button_text = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text_long = 2130968605;
			
			// aapt resource value: 0x7f04002a
			public const int compass = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int custom_info_contents = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int custom_info_window = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int default_info_window = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int demo_title = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int down_arrow = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int drag_melbourne = 2130968624;
			
			// aapt resource value: 0x7f040032
			public const int events_demo = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int events_description = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int fill_alpha = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int fill_hue = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int go_to_bondi = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int go_to_sydney = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int groundoverlay_demo = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int groundoverlay_description = 2130968633;
			
			// aapt resource value: 0x7f040031
			public const int hue = 2130968625;
			
			// aapt resource value: 0x7f04003a
			public const int hybrid = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int layers_demo = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int layers_description = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int left_arrow = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int locationsource_demo = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int locationsource_description = 2130968639;
			
			// aapt resource value: 0x7f040044
			public const int map_not_ready = 2130968644;
			
			// aapt resource value: 0x7f040040
			public const int marker_demo = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int marker_description = 2130968641;
			
			// aapt resource value: 0x7f040045
			public const int move_the_camera = 2130968645;
			
			// aapt resource value: 0x7f040042
			public const int multi_map_demo = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int multi_map_description = 2130968643;
			
			// aapt resource value: 0x7f040046
			public const int my_location = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int mylocation_button = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int mylocation_layer = 2130968648;
			
			// aapt resource value: 0x7f040049
			public const int no_demos = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int normal = 2130968650;
			
			// aapt resource value: 0x7f04004b
			public const int options_demo = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int options_description = 2130968652;
			
			// aapt resource value: 0x7f04004d
			public const int polygon_demo = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int polygon_description = 2130968654;
			
			// aapt resource value: 0x7f040025
			public const int polygonline = 2130968613;
			
			// aapt resource value: 0x7f04004f
			public const int polyline_demo = 2130968655;
			
			// aapt resource value: 0x7f040050
			public const int polyline_description = 2130968656;
			
			// aapt resource value: 0x7f040051
			public const int programmatic_demo = 2130968657;
			
			// aapt resource value: 0x7f040052
			public const int programmatic_description = 2130968658;
			
			// aapt resource value: 0x7f040054
			public const int properties_sydney_polygon = 2130968660;
			
			// aapt resource value: 0x7f040053
			public const int properties_sydney_polyline = 2130968659;
			
			// aapt resource value: 0x7f040056
			public const int raw_mapview_demo = 2130968662;
			
			// aapt resource value: 0x7f040057
			public const int raw_mapview_description = 2130968663;
			
			// aapt resource value: 0x7f040058
			public const int reset_map = 2130968664;
			
			// aapt resource value: 0x7f040059
			public const int retain_map = 2130968665;
			
			// aapt resource value: 0x7f04005a
			public const int retain_map_description = 2130968666;
			
			// aapt resource value: 0x7f04005b
			public const int right_arrow = 2130968667;
			
			// aapt resource value: 0x7f040055
			public const int rotate = 2130968661;
			
			// aapt resource value: 0x7f04005c
			public const int satellite = 2130968668;
			
			// aapt resource value: 0x7f04005d
			public const int scroll = 2130968669;
			
			// aapt resource value: 0x7f04005e
			public const int stop_animation = 2130968670;
			
			// aapt resource value: 0x7f04005f
			public const int stroke_width = 2130968671;
			
			// aapt resource value: 0x7f040060
			public const int tap_instructions = 2130968672;
			
			// aapt resource value: 0x7f040061
			public const int terrain = 2130968673;
			
			// aapt resource value: 0x7f040062
			public const int tile_overlay_demo = 2130968674;
			
			// aapt resource value: 0x7f040063
			public const int tile_overlay_description = 2130968675;
			
			// aapt resource value: 0x7f040064
			public const int tilt = 2130968676;
			
			// aapt resource value: 0x7f040065
			public const int traffic = 2130968677;
			
			// aapt resource value: 0x7f040066
			public const int transparency = 2130968678;
			
			// aapt resource value: 0x7f040067
			public const int uisettings_demo = 2130968679;
			
			// aapt resource value: 0x7f040068
			public const int uisettings_description = 2130968680;
			
			// aapt resource value: 0x7f040069
			public const int up_arrow = 2130968681;
			
			// aapt resource value: 0x7f04006a
			public const int width = 2130968682;
			
			// aapt resource value: 0x7f04006b
			public const int zoom_buttons = 2130968683;
			
			// aapt resource value: 0x7f04006c
			public const int zoom_gestures = 2130968684;
			
			// aapt resource value: 0x7f04006d
			public const int zoom_in = 2130968685;
			
			// aapt resource value: 0x7f04006e
			public const int zoom_out = 2130968686;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771984,
					2130771985,
					2130771986};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
